apiVersion: v1
kind: Service
metadata:
  name: javasample
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: javasample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javasample
spec:
  selector:
    matchLabels:
      app: javasample
  template:
    metadata:
      labels:
        app: javasample
    spec:
      containers:
      - name: javasample
        image: javasample
        ports:
          - containerPort: 8080
